// Screen 02 breakdown and the one total-spending number everyone uses (TASKS.md Decisions #3).
// breakdown.json is generated by pipeline/build_breakdown.py; don't edit it by hand.

import data from './breakdown.json'
import type { Source } from './types'

export type BreakdownItem = {
  name: string
  description: string
  official_name: string
  department: string
  dept_code: string
  program_code: string
  amount: number
  percent: number
}

export type Breakdown = {
  fiscal_year: string
  total_federal_spending: number
  program_count: number
  items: BreakdownItem[]
  source: Source
}

export const breakdown: Breakdown = data

// Sum of `expenditure` in programs_spending.csv for 2024-25.
export const TOTAL_FEDERAL_SPENDING = breakdown.total_federal_spending

/**
 * Purpose:
 *	Work out how much of a spending item the user's own federal tax paid for. Same formula on every screen.
 *
 * Args:
 *	- federalTax: the user's estimated federal income tax in dollars, from estimateTax().federal
 *	- amount: the spending item's cost in dollars
 *
 * Returns:
 *	number: the user's share in dollars, unrounded
 */
export function yourShare(federalTax: number, amount: number) {
  return federalTax * (amount / TOTAL_FEDERAL_SPENDING)
}
